client_id = "Insert Client ID"
client_secret = "Insert Client Secret"
password = "Insert password"
username = "Insert username"
user_agent = "Give a name here so the admins know who is logging in. I use '/u/useful_bot by /u/coolaspie' "
