name: Python Lint

on:
  push:
  schedule:
  - cron: "0 2 * * 0"

jobs:
  Lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/requirements-dev.txts') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install -r requirements-dev.txt
    - name: Pylint
      run: pylint useful_bot
    - name: Flake8
      run: flake8 useful_bot
    - name: Bandit
      run: bandit -r --skip B322 useful_bot
    - name: Black
      run: black --check useful_bot
